---
- name: Add metabase user
  ansible.builtin.include_tasks: user.yml

- name: Install metabase
  ansible.builtin.include_tasks: install.yml

- name: Configure metabase
  ansible.builtin.include_tasks: configure.yml
