---
- name: Check for old versions
  ansible.builtin.find:
    paths: "{{ metabase_app_dir }}"
    file_type: any
    excludes: "{{ metabase_version }}"
  become: true
  register: old_versions

- name: Delete old versions
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  become: true
  loop: "{{ old_versions.files }}"
