---

- name: Create group
  ansible.builtin.group:
    name: "{{ metabase_group }}"
  become: true

- name: Create user
  ansible.builtin.user:
    name: "{{ metabase_user }}"
    group: "{{ metabase_group }}"
  become: true
