---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: Restart metabase
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: true
    name: metabase

- name: Remove old versions
  ansible.builtin.include_tasks: upgrade_cleanup.yml
  when: metabase_upgrade_cleanup
